"""empty message

Revision ID: 38c63584fbe1
Revises: 0eaf02a0a38e
Create Date: 2018-07-04 09:40:37.139103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c63584fbe1'
down_revision = '0eaf02a0a38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('dateReviewed', sa.Date(), nullable=True))
    op.add_column('node', sa.Column('dateTried', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'dateTried')
    op.drop_column('node', 'dateReviewed')
    # ### end Alembic commands ###
