"""empty message

Revision ID: 44b23988818c
Revises: 38c63584fbe1
Create Date: 2018-07-06 11:37:09.914829

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '44b23988818c'
down_revision = '38c63584fbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # updated default command to add default date for users already added
    op.add_column('user', sa.Column('dateAddeded', sa.Date(), nullable=False, server_default='2018/07/06'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dateAddeded')
    # ### end Alembic commands ###
