"""empty message

Revision ID: 52f5522920c0
Revises: 44b23988818c
Create Date: 2018-07-06 20:40:49.342626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f5522920c0'
down_revision = '44b23988818c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dateAddeded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dateAddeded', sa.DATE(), server_default=sa.text("'2018-07-06'"), nullable=False))
    # ### end Alembic commands ###
