"""empty message

Revision ID: a8bedc48b160
Revises: 52f5522920c0
Create Date: 2018-07-28 08:47:36.098436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bedc48b160'
down_revision = '52f5522920c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('sortIndex', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'sortIndex')
    # ### end Alembic commands ###
